import { Footer, Navbar } from "components";
import { Poppins,Tajawal } from "next/font/google";
import ClientProviders from "providers/use-client-providers";
import { useTranslations } from 'next-intl';
import "styles/globals.css";

const poppins = Poppins({weight:"400", subsets: ["latin"] });
const tajawal = Tajawal({weight:"400", subsets: ["arabic"] });


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children,params }) {

  const t=useTranslations("Navbar")
  const globals=useTranslations("Globals")

  const footer=useTranslations("Footer")
  
  return (
    <html dir={params.locale==="ar"?"rtl":"ltr"} lang={params.locale} style={{ 
      fontFamily: "'Poppins', sans-serif",
    fontWeight: 300,
    fontStyle: "normal"
    }}>
      <body className={params.locale==="ar"?tajawal.className:poppins.className}>

        <Navbar 
          locale={params.locale}
          translation={{
            home:t("home"),
            services:t("services"),
            about:t("about"),
            contact:t("contact"),
            languages:globals("languages"),
            close:globals("close")
            }}
        />
        <ClientProviders>
          {children}
        </ClientProviders>
        <Footer t={footer}/>
      </body>
    </html>
  );
}
